title: Ola Babajide
# logo: /assets/img/headshot_circle.png
logo: https://github.com/babajideolayemi28/business-analyst-portfolio.io/blob/main/images/Picture6.jpg
description: Business Analyst Project
show_downloads: true
theme: jekyll-theme-minimal

